name: FC Kernels

on:
  push:

permissions:
  id-token: write

jobs:
  publish:
    name: Upload kernels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Build kernels
        run: sudo make build

      - name: Upload kernels
        if: github.ref_name == 'main'
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "./builds"
          destination: ${{ vars.GCP_BUCKET_NAME }}/kernels
          gzip: false
          parent: false

      - name: Upload kernels as artifact
        if: github.ref_name != 'main'
        uses: actions/upload-artifact@v4
        with:
          name: kernels-${{ github.run_id }}
          path: ./builds
          retention-days: 7
