name: FC Kernels

on:
  push:

permissions:
  id-token: write

jobs:
  publish:
    name: Upload kernels
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Service Account
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Build kernels
        run: sudo make build

      - name: Set bucket based on branch
        id: set-bucket
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "DESTINATION=${{ secrets.GCP_BUCKET_NAME }}/kernels" >> $GITHUB_OUTPUT
          else
            echo "DESTINATION=${{ secrets.GCP_DEV_BUCKET_NAME }}/${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Upload kernels
        uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "./builds"
          destination: ${{ steps.set-bucket.outputs.DESTINATION }}/kernels
          gzip: false
          parent: false
